version: '3'
services:
  nginx:
    build: "./web/docker/local/nginx"
    container_name: vuesplash-nginx
    ports:
      - "90:90"
    volumes:
      - ./web/public:/var/www/html/vuesplash/public
      - ./web/docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: .
    volumes:
      - ./web:/var/www/html/vuesplash
    ports:
      - "8081:8081"
      - "3000:3000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_DB=vuesplash
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./web/storage/postgresql:/var/lib/postgresql/data