version: '3'
services:
  nginx:
    build: "./web/docker/local/nginx"
    container_name: vuesplash-nginx
    ports:
      - "90:90"
    volumes:
      - ./web/public:/var/www/html/vuesplash/public
      - ./web/docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: .
    volumes:
      - ./web:/var/www/html/vuesplash
    ports:
      - "8081:8081"
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: vuesplash
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./web/storage/mysql:/var/lib/mysql